# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.500'

  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: 'test/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --logger trx'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'